Added more informative messages to the barcode schemas. New schema: 10xV1i (interleaved *RA*.fastq.gz files).
Former-commit-id: 1d54fb3c0f8aaeb6207d54e541de808df191ffdd

diff --git a/sh/fastq2bam b/sh/fastq2bam
--- a/sh/fastq2bam
+++ b/sh/fastq2bam
@@ -16,8 +16,8 @@ function perror {
 }
 
 function usage() {
-    echo "Usage: fastq2bam -s scheme -b out_bam -1 fastqfile1 [ -2 fastqfile2 -3 fastqfile3 -4 fastqfile4]"
-    echo "scheme: 10xV1 10xV1a 10xV2 drop-seq none"
+    echo "Usage: fastq2bam -s schema -b out_bam -1 fastqfile1 [ -2 fastqfile2 -3 fastqfile3 -4 fastqfile4]"
+    echo "barcode schema: 10xV1 10xV1i 10xV1a 10xV2 drop-seq none"
 }
 
 function gen_bam() {
@@ -30,7 +30,7 @@ function gen_bam() {
 
 ##########################################################
 ##
-scheme=
+schema=
 bam_file=
 fastq_file1=
 fastq_file2=
@@ -41,8 +41,8 @@ while getopts "b:s:a:1:2:3:4:h"  Option
 do
     case $Option in
         b ) bam_file=$OPTARG;;
-	s ) scheme=$OPTARG;;
-	a ) scheme=$OPTARG;;
+	s ) schema=$OPTARG;;
+	a ) schema=$OPTARG;;
 	1 ) fastq_file1=$OPTARG;;
 	2 ) fastq_file2=$OPTARG;;
 	3 ) fastq_file3=$OPTARG;;
@@ -51,41 +51,45 @@ do
     esac
 done
 
-if [ "$*-" == "-" ] || [ "$scheme-" == "-" ]; then
+if [ "$*-" == "-" ] || [ "$schema-" == "-" ]; then
     usage
     exit 1
 fi
 
-#scheme=$1
+#schema=$1
 #out_bam=$2
 #shift 2
 
-pinfo scheme=$scheme
+pinfo schema=$schema
 pinfo bam_file=$bam_file
 pinfo fastq1=$fastq_file1
 pinfo fastq2=$fastq_file2
 pinfo fastq3=$fastq_file3
 
 
-if [ "$scheme-"  == "10xV2-" ]; then
-    # index1=R1 file index2=I1 index3=I5 reads=R2
+if [ "$schema-"  == "10xV2-" ]; then
+    # index1=R1 file index2=I1 reads=R2
     if [ "$fastq_file2-"  == "-" ]; then
-	echo "Missing files for $scheme"
+	echo "Missing files for $schema:"
+	echo "-1 cell#16|umi#10 -2 cdna -3 [-3 sample#8]"
+	echo "e.g., -1 *R1*.fastq.gz -2 *R2*.fastq.gz [-3 *I1*.fastq.gz]"
 	usage
 	exit 1
     fi
     cmd="fastq_pre_barcodes --read1 $fastq_file2 --index1 $fastq_file1 --umi_read index1 --umi_offset 16 --umi_size 10 --cell_read index1 --cell_offset 0 --cell_size 16"
-    if [ "$fastq_file4-" != "-" ]; then
+    if [ "$fastq_file3-" != "-" ]; then
 	cmd="$cmd --index2 $fastq_file3 --sample_read index2 --sample_offset 0 --sample_size 8" 
     fi
     gen_bam $cmd
     exit 0
 fi
 
-if [ "$scheme-"  == "10xV1-" ]; then
+if [ "$schema-"  == "10xV1-" ]; then
     # index1=read2/I7, index2=I5
     if [ "$fastq_file2-"  == "-" ]; then
-	echo "Missing files for $scheme"
+	echo "Missing files for $schema:"
+	echo "-1 cdna  -2 cell#14|umi#10 [-3 sample#8]"
+	echo "e.g., -1 *R1*.fastq.gz -2 *R2*.fastq.gz  [-3 *I5*.fastq.gz]"
 	usage
 	exit 1
     fi
@@ -98,13 +102,15 @@ if [ "$scheme-"  == "10xV1-" ]; then
 fi
 
 
-if [ "$scheme-"  == "10xV1a-" ]; then
+if [ "$schema-"  == "10xV1a-" ]; then
     # fastq_file1 = read_RA*_1 = cdna
     # fastq_file2 = index3=read_RA*_2 = UMI
     # fastq_file3 = index1=*I1* = cell barcode
     # fastq_file4 = index2=*I2* = sample barcodes
     if [ "$fastq_file2-"  == "-" ] || [ "$fastq_file3-" == "-" ]; then
-	echo "Missing files for $scheme"
+	echo "Missing files for $schema:"
+	echo "-1 cdna  -2 umi#10 -3 cell#14 [-4 sample#8]"
+	echo "e.g., -1 *RA_1.fastq.gz -2 *RA_2.fastq.gz -3 *I1*.fastq.gz [-4 *I2*.fastq.gz]"
 	usage
 	exit 1
     fi
@@ -117,10 +123,33 @@ if [ "$scheme-"  == "10xV1a-" ]; then
     exit 0
 fi
 
-if [ "$scheme-"  == "dropseq-" ]; then
-    pinfo "scheme $scheme under development"
+if [ "$schema-"  == "10xV1i-" ]; then
+    # fastq_file1 = read_RA*_1 = cdna & index3=read_RA*_2 = UMI
+    # fastq_file2 = index1=*I1* = cell barcode
+    # fastq_file3 = index2=*I2* = sample barcodes
     if [ "$fastq_file2-"  == "-" ]; then
-	echo "Missing files for $scheme"
+	echo "Missing files for $schema:"
+	echo "-1 cdna/umi#10 -2 cell#14  [-3 sample#8]"
+	echo "e.g., -1 *RA*.fastq.gz -2 *I1*.fastq.gz [-3 *I2*.fastq.gz]"
+	usage
+	exit 1
+    fi
+
+    cmd="fastq_pre_barcodes --read1 $fastq_file1 --index3 $fastq_file1 --index1 $fastq_file2 --umi_read index3 --umi_offset 0 --umi_size 10 --cell_read index1 --cell_offset 0 --cell_size 14 --interleaved read1,index3"
+    if [ "$fastq_file3-"  != "-" ]; then
+	cmd="$cmd  --index3 $fastq_file3 --sample_read index2 --sample_offset 0 --sample_size 8"
+    fi
+    gen_bam $cmd
+    exit 0
+fi
+
+
+if [ "$schema-"  == "dropseq-" ]; then
+    pinfo "schema $schema under development"
+    if [ "$fastq_file2-"  == "-" ]; then
+	echo "Missing files for $schema:"
+	echo "-1 umi#8|cell#12 -2 cdna"
+	echo "e.g., -1 *_1.fastq.gz -2 *_2.fastq.gz"
 	usage
 	exit 1
     fi
@@ -130,7 +159,7 @@ if [ "$scheme-"  == "dropseq-" ]; then
     exit 0
 fi
 
-if [ "$scheme-"  == "none-" ]; then
+if [ "$schema-"  == "none-" ]; then
     cmd="fastq_pre_barcodes --read1 $fastq_file1"
     if [ "$fastq_file2-" != "-" ]; then
 	cmd="$cmd  --read2 $fastq_file2" 
@@ -139,7 +168,7 @@ if [ "$scheme-"  == "none-" ]; then
     exit 0
 fi
 
-pinfo "Unknown  scheme $scheme"
+pinfo "Unknown  schema $schema"
 exit 1
 
 
