Added drop-seq

diff --git a/sh/fastq2bam b/sh/fastq2bam
--- a/sh/fastq2bam
+++ b/sh/fastq2bam
@@ -16,7 +16,7 @@ function perror {
 }
 
 function usage() {
-    echo "Usage: fastq2bam -a format -b out_bam -1 fastqfile1 [ -2 fastqfile2 -3 fastqfile3 -4 fastqfile4]"
+    echo "Usage: fastq2bam -a scheme -b out_bam -1 fastqfile1 [ -2 fastqfile2 -3 fastqfile3 -4 fastqfile4]"
     echo "scheme: 10xV1 10xV1p 10xV2 drop-seq none"
 }
 
@@ -113,7 +113,15 @@ if [ "$scheme-"  == "10xV1p-" ]; then
 fi
 
 if [ "$scheme-"  == "dropseq-" ]; then
-    pinfo "Not implemented  scheme $scheme"
+    pinfo "scheme $scheme under development"
+    if [ "$fastq_file2-"  == "-" ]; then
+	echo "Missing files for $scheme"
+	usage
+	exit 1
+    fi
+    cmd="fastq_pre_barcodes --read1 $fastq_file2 --index1 $fastq_file1 --umi_read index1 --umi_offset 12 --umi_size 8 --cell_read index1 --cell_offset 0 --cell_size 12"
+    gen_bam $cmd
+
     exit 0
 fi
 
